language: java

# Don't use shallow clone to allow sonarcloud to track changes
git:
  depth: false

addons:
  apt:
    packages:
    - libgconf-2-4
  sonarcloud:
    organization: "bdeployteam"
    token:
      secure: "cvsPSWB89s79D1N/5/vi3UKgQQpOi0UxeMtA5BhQZA7zn+FTbCdWIdtwECI6ZWI3OuISyAw1yfhX0uUmgHP7l1sphrspYP9pO5872r9y1kLcGIDZlSBNDZfaeSYf90R3eayP84Qvzm+7mwghqgOEkuenEGayVUSuf3edEuqPMhuj+yW09fMTwqYOkGUvVsl/yho43XjWqPLeXLzD8kAlhIFg8+SXem8roJHBoCnMmAmFWfYGJx5amyRHTvfLZXzRcMjnBZwsTbrielQa5xT46vp9+ueBpHxk/8bOgSD+zwUomS0T8E7EBMGxj5QY79U6wI2Ilh64Boc00bHUmJKwBldrCy4v+IE+y+82txPEPo6k3NNx9hqu9OBYbFBCoe5mIBAXyRg9Jm3jQXkGDL2wXTdzqr47JtrwXFlcT96Tv1aaDPLgvfmhuaBfSBjnl0vf65LmXQlfmXNpkl5bWMdJr7dLY7IngqpiDq344kKbm5GUNZkhKhSwjlimIbeq61Sh2VNSRpdiAtiboZ6shnZ3Sj/EM4oovvaRabv3WRokqKF5uTBqH6BDfyET19I8R8qGP5LZt3ZAbVshXvCOiccqmmRJusAZAmYMMzQX6/y8ZrULUYdD3dVhILsEVnXVAqi/kt0kUvmWsA9xmrQxgk0Fsfk90DqmuZCuuBP2PPk2WFM="

env:
  - NODE_VERSION="10"

before_install:
  - nvm install $NODE_VERSION
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

install:
  - . ./install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'

script:
  - ./gradlew clean build sonarqube --scan -s -PverboseTest -PrecordCypress

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.npm
    - $HOME/.cache

