name: "Demo Product"
product: "io.bdeploy/demo"
vendor: BDeploy Team
applications:
- "server-app"
- "client-app"

instanceTemplates:
- "product-template.yaml"

applicationTemplates:
- "app-templates/server-with-sleep.yaml"

versionFile: "product-version.yaml"


