version: "2.0.0"
appInfo:
  server-app:
    WINDOWS: "server-app/app-info.yaml"
    LINUX: "server-app/app-info.yaml"
    #MACOS: "server-app/app-info.yaml"
  client-app:
    WINDOWS: "client-app/app-info.yaml"
    LINUX: "client-app/app-info.yaml"
    #MACOS: "client-app/app-info.yaml"
