name: Default Configuration
description: "Creates an instance with the default server and client configuration"

variables:
  - uid: text-param
    name: "Text Value"
    description: "A text to set"
    suggestedValues:
    - 'Test Value'
    - 'Another Suggested Value'

groups:
- name: "Server Apps"
  description: "All server applications"

  applications:
  - application: server-app
    name: "Server No Sleep"
    description: "Server application which immediately exits"
    processControl:
      startType: "MANUAL_CONFIRM"
    startParameters:
    - uid: param.text
      value: "{{T:text-param}}"
  - template: server-with-sleep
  - template: server-with-sleep
    name: "Another Server With Sleep"
    startParameters:
    - uid: param.text
      value: "{{T:text-param}}"
    
- name: "Client Apps"
  type: CLIENT
  description: "All client applications"
  
  applications:
  - application: client-app
    name: "Client {{T:text-param}}"
    description: "A default client application."
    
