name: "Demo Product"
product: "io.bdeploy/demo"
vendor: BDeploy Team
applications:
- "server-app"
- "client-app"
configTemplates: config

instanceTemplates:
- "product-template.yaml"

applicationTemplates:
- "app-templates/server-with-sleep.yaml"

parameterTemplates:
- "param-templates/shared.yaml"

instanceVariableTemplates:
- "variable-template.yaml"

versionFile: "product-version.yaml"


