name: Default Configuration
description: "Creates an instance with the default server and client configuration"

templateVariables:
  - uid: text-param
    name: "Text Value"
    description: "A text to set"
    suggestedValues:
    - 'Test Value'
    - 'Another Suggested Value'

instanceVariables:
  io.bdeploy.test:
    value: "Variable Value"
    description: "Some test variable"
  io.bdeploy.another:
    value: "Another Variable Value"
    description: "Yet another test variable"

processControlGroups:
  - name: "First Group"
    startType: "PARALLEL"
    startWait: "WAIT"
  - name: "Second Group"
    stopType: "PARALLEL"

groups:
- name: "Server Apps"
  description: "All server applications"

  applications:
  - application: server-app
    name: "Server No Sleep"
    description: "Server application which immediately exits"
    preferredProcessControlGroup: "First Group"
    processControl:
      startType: "MANUAL_CONFIRM"
    startParameters:
    - uid: param.text
      value: "{{T:text-param}}"
  - template: server-with-sleep
    startParameters:
    - uid: param.text
      value: "{{X:io.bdeploy.test}}"
  - template: server-with-sleep
    name: "Another Server With Sleep"
    preferredProcessControlGroup: "Second Group"
    startParameters:
    - uid: param.text
      value: "{{T:text-param}}"
    
- name: "Client Apps"
  type: CLIENT
  description: "All client applications"
  
  applications:
  - application: client-app
    name: "Client {{T:text-param}}"
    description: "A default client application."
    
