name: BDeploy CI - Linux
on: [push]

jobs:
  build:
    name: Build and test on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v3
        
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build and Test
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew --stacktrace --scan clean build sonarqube -PrecordCypress -PcypressTimeout=80000 '-Dtestlogger.theme=plain-parallel' -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}

