name: BDeploy CI - Linux
on: [push]

jobs:
  build:
    name: Build and test on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v2
        
    - name: Cache Cypress
      uses: actions/cache@v1
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress

    - name: Cache NPM
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build and Test
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew --stacktrace clean build releaseTest sonarqube -PrecordCypress '-Dtestlogger.theme=plain-parallel' -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}
