name: BDeploy CI - Mac
on: [push]

jobs:
  build:
    name: Build and test on Mac
    runs-on: macos-latest

    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v3
        
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build and Test
      run: ./gradlew -stacktrace clean build -x runCypressHeadless '-Dtestlogger.theme=plain-parallel'

