name: BDeploy CI - Windows
on: [push]

jobs:
  build:
    name: Build and test on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v2
        
    - name: Cache Cypress
      uses: actions/cache@v1
      with:
        path: ~\AppData\Local\Cypress\Cache
        key: ${{ runner.os }}-cypress

    - name: Cache NPM
      uses: actions/cache@v1
      with:
        path: ~\AppData\Roaming\npm-cache
        key: ${{ runner.os }}-node-${{ hashFiles('**\package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build and Test
      run: ./gradlew --stacktrace clean build releaseTest -PrecordCypress -PcypressBrowser=electron -PcypressNoCoverage=yes '-Dtestlogger.theme=plain-parallel'
